# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ON1V3U2hQul5YM4uuEI8eURenfVfdKH3
"""

a =True
b= False
print(a or a and b and a )


l = list("1234")
l[0]= l[1] =5
print(l)

for i in range(1):
  print(i, end=' ')
else:
  print("Executed")

def fun():
  for x in range(22,23,24):
    print(x)
fun()

def f1():
  x =100
  return x
x = f1()+1
print(x)

def f():
  pass
print(type(f()))

print("Hello World!".capitalize())

aTuple = ("Orange")
print(type(aTuple))

def fun():
  return 55+int(55.55)
print(fun())

def python():
  return python()+1
print(python)

print("abc. DEF".capitalize())